version: "3.8"

services:
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"

  ai_bot_1:
    build: ./AI_Bot
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "5001:5000"
