name: Deploy AI Bot

on:
  push:
    branches:
      - main  # Запуск при пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Устанавливаем SSH-ключ
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Подключаемся к серверу и деплоим
        run: |
          ssh -o StrictHostKeyChecking=root@37.27.192.143 << 'EOF'
            cd /path/to/your-bot
            git pull origin main
            docker-compose down
            docker-compose up --build -d
          EOF
